### ISSUE TITLE
path too long, it can't save the image

### ISSUE THREAD

**Issue by LockMan007** [XmYx/ainodes-pyside#4]
When I use a prompt with about 15 words (approximately), it tries to make a folder + filename with the prompt and it becomes too long and windows can't handle it.
Please add the option to truncate filenames and folders.

Traceback (most recent call last):
  File "D:\apps\AI\2.0\ainodes-pyside-sd_v2\backend\worker.py", line 70, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\apps\AI\2.0\ainodes-pyside-sd_v2\frontend\ui_deforum.py", line 162, in run_deforum_six_txt2img
    self.deforum_six.run_deforum_six(W=int(params['W']),
  File "D:\apps\AI\2.0\ainodes-pyside-sd_v2\backend\deforum\deforum_adapter.py", line 501, in run_deforum_six
    render_image_batch(args, prompts, root, image_callback=image_callback, step_callback=step_callback)
  File "D:\apps\AI\2.0\ainodes-pyside-sd_v2\backend\deforum\six\render.py", line 145, in render_image_batch
    image.save(os.path.join(outfolder, filename))
  File "D:\apps\AI\2.0\ainodes-pyside-sd_v2\venv\lib\site-packages\PIL\Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'data/output/txt2img\\20221124142541

**Comment by osi1880vr** [comment]
thats new, can you provide the prompt or at least a string same lenght? I think we do a sanitise of that prompt and then write it to the disk. it never happend here and im keen to use whole novels to prompt.... but we figure it out. a workaround could be this, in the settings at config/ainodes/ settings.json you will find a value called pathmode, if you set it to anything but subfolders it will not generate a folder with the prompt name it will just put all images into one folder. this should help get around the issue for now and for until we understand whats going wrong with your names

**Comment by LockMan007** [comment]
> 

This worked. Thanks.
        "pathmode": ".",
